dsme-wdd-wd.c: Fix GCC string truncation error.
This fixes issue #297 on the Maemo Leste bugtracker.

Compiling with GCC 8.3.0 gives the following error:
dsme-wdd-wd.c:236:38: error: 'snprintf' output may be truncated before the last format character [-Werror=format-truncation=]
                      "/dev/watchdog%d", i);
                                      ^
dsme-wdd-wd.c:235:13: note: 'snprintf' output between 15 and 16 bytes into a destination of size 15
             snprintf(watchdog_path, sizeof(watchdog_path),
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                      "/dev/watchdog%d", i);
                      ~~~~~~~~~~~~~~~~~~~~~

Some fiddling around seems to confirm this is a false positive.

We have fixed this however by changing the array size to 32 instead of
disabling the check in question.